name: science4cast
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2022.12.7=h5b45459_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py310h59b6b97_0
  - cpuonly=2.0=0
  - cryptography=39.0.1=py310h21b164f_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - filelock=3.9.0=py310haa95532_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jinja2=3.1.2=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - kiwisolver=1.4.4=py310h476a331_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libclang=12.0.0=default_h627e005_2
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.2=hd77b12b_6
  - libiconv=1.17=h8ffe710_0
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h8cc25b3_0
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.10.3=h0ad7f3c_0
  - libxslt=1.1.37=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib=3.7.1=py310h5588dad_0
  - matplotlib-base=3.7.1=py310h4ed8f06_1
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - mpmath=1.2.1=py310haa95532_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - networkx=2.8.4=py310haa95532_0
  - numpy=1.24.3=py310hdc03b94_0
  - numpy-base=1.24.3=py310h3caf3d7_0
  - openssl=1.1.1t=h2bbff1b_0
  - packaging=23.0=py310haa95532_0
  - pcre=8.45=h0e60522_0
  - pillow=9.4.0=py310hd77b12b_0
  - pip=23.0.1=py310haa95532_0
  - ply=3.11=py_1
  - pooch=1.4.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py310haa95532_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.11=h966fe2a_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.0=py3.10_cpu_0
  - pytorch-mutex=1.0=cpu
  - qt-main=5.15.2=he8e5bd7_7
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtwebkit=5.212=h2bbfb41_5
  - requests=2.29.0=py310haa95532_0
  - scipy=1.10.1=py310hb9afe5d_0
  - setuptools=66.0.0=py310haa95532_0
  - sip=6.6.2=py310h8a704f9_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - sympy=1.11.1=py310haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd8ed1ab_0
  - torchaudio=2.0.0=py310_cpu
  - torchvision=0.15.0=py310_cpu
  - tornado=6.2=py310he2412df_0
  - typing_extensions=4.5.0=py310haa95532_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.15=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.38.4=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.2.10=h8cc25b3_1
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
prefix: C:\Users\mkrenn\.conda\envs\science4cast
